# Generated by Django 5.0.2 on 2026-08-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_position_user_positon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='positon',
            new_name='position',
        ),
    ]
