# Generated by Django 5.0.2 on 2026-09-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
