# Generated by Django 5.0.2 on 2026-09-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTestMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ct2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ct3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_test_marks', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_test_marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='classtestmark',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_student_course_ct'),
        ),
    ]
