# Generated by Django 5.0.2 on 2026-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='class_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('course', 'class_number'), name='unique_course_class_number'),
        ),
    ]
