# Generated by Django 5.0.2 on 2026-09-03 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attendancesession_class_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10, null=True)),
                ('method', models.CharField(blank=True, choices=[('face', 'Face Verification'), ('manual', 'Manual')], max_length=10, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('attendance_session', 'student'), name='unique_attendance_per_student'),
        ),
    ]
