# Generated by Django 5.0.2 on 2026-09-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
    ]
