# Generated by Django 5.0.2 on 2026-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attendancesession_is_held'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
