# Generated by Django 5.0.2 on 2026-09-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_attendancesession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
