# Generated by Django 5.0.2 on 2026-09-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
