# Generated by Django 5.0.2 on 2026-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_faces/'),
        ),
    ]
