# Generated by Django 5.0.2 on 2026-09-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bus_notices/pdf/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bus_notices/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
