# Generated by Django 5.0.2 on 2026-09-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_busnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtestmark',
            name='semester_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
