# Generated by Django 5.0.2 on 2026-09-17 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_classtestmark_semester_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterQuestionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semester_question_pattern', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveIntegerField(default=1)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='core.semesterquestionpattern')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SemesterSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_label', models.CharField(max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='core.semesterquestionset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SemesterSubQuestionMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subquestion_marks', to=settings.AUTH_USER_MODEL)),
                ('subquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='core.semestersubquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='semesterquestionset',
            constraint=models.UniqueConstraint(fields=('pattern', 'set_name'), name='unique_set_name_per_pattern'),
        ),
        migrations.AddConstraint(
            model_name='semestersubquestion',
            constraint=models.UniqueConstraint(fields=('question_set', 'question_label'), name='unique_subquestion_per_set'),
        ),
        migrations.AddConstraint(
            model_name='semestersubquestionmark',
            constraint=models.UniqueConstraint(fields=('student', 'subquestion'), name='unique_student_subquestion_mark'),
        ),
    ]
