# Generated by Django 5.0.2 on 2026-09-19 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_semesterquestionpattern_semesterquestionset_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semestersubquestionmark',
            name='unique_student_subquestion_mark',
        ),
        migrations.RemoveField(
            model_name='semestersubquestionmark',
            name='subquestion',
        ),
        migrations.AddField(
            model_name='semestersubquestionmark',
            name='sub_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='core.semestersubquestion'),
        ),
        migrations.AlterField(
            model_name='semestersubquestion',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='core.semesterquestionset'),
        ),
        migrations.AddConstraint(
            model_name='semestersubquestionmark',
            constraint=models.UniqueConstraint(fields=('student', 'sub_question'), name='unique_student_subquestion_mark'),
        ),
    ]
