# Generated by Django 4.2.30 on 2026-09-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestersubquestion',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='core.semesterquestionset'),
        ),
    ]
